// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7L1t7b3zFXm9k43dHEfdWrxPi3y9hBB4',
    appId: '1:244061176148:android:808986f70fc52ec08b48c1',
    messagingSenderId: '244061176148',
    projectId: 'flutter-app-distribution-c94b7',
    databaseURL: 'https://flutter-app-distribution-c94b7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-distribution-c94b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM8vPTvVJKOKbCGRum9mG4MgdVvAnPit8',
    appId: '1:244061176148:ios:8e2301d3b29ce63e8b48c1',
    messagingSenderId: '244061176148',
    projectId: 'flutter-app-distribution-c94b7',
    databaseURL: 'https://flutter-app-distribution-c94b7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-distribution-c94b7.appspot.com',
    iosBundleId: 'com.example.docdoc',
  );
}
